// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"testutil"
	"testing"
)

func Test_c(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithFile(t, mostFrequentIDs, "c.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-390/problems/most-frequent-ids/
// https://leetcode.cn/problems/most-frequent-ids/
