// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"testutil"
	"testing"
)

func Test_d(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithFile(t, stringIndices, "d.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-390/problems/longest-common-suffix-queries/
// https://leetcode.cn/problems/longest-common-suffix-queries/
